image: gitpod/workspace-docker

ports:
  - port: 6052
    onOpen: open-browser
    visibility: private

tasks:
  - name: Start ESPHome Dashboard
    init: |
      docker compose pull
    command: |
      docker compose up
